version: '3.8'
services:
  faster-whisper-server:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - faster_whisper:/models
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

volumes:
  faster_whisper:
